export const langs =
{
  "en": "English",
  "es": "Español",
  "fr": "Français",
  "it": "Italiano",
  "pt": "Português"
};

export const language =
{
  en:
  {
    liSimul: "Simulation",
    liBgp: "Background physics",
    liCode: "Code",
    selLang: "Select language",
    decSep: ", ",
    cZeroToInf: "[0, ∞)",
    oZeroToInf: "(0, ∞)",
    minfToInf: "(-∞, ∞)",
    cZeroToOne: "[0, 1)",
    mainTitle: "Relativistic motion of a charged and massive particle on a uniform and constant electromagnetic field",
    initCondF: "Initial conditions: fields",
    EFtitle: "Electric field",
    MFtitle: "Magnetic field",
    MagnTitle: "Norm",
    UnitDirTitle: "Unit vector",
    prBtn: "Pseudorandom",
    SIPref: "Prefix",
    initCondP: "Initial conditions: particle",
    inMassTitle: "Inertial mass",
    EChTitle: "Electric charge",
    loadPreset: "Load preset: ",
    electron: "Electron (e⁻)",
    positron: "Positron (e⁺)",
    proton: "Proton (p⁺)",
    antiproton: "Antiproton (p⁻)",
    Helium4Nucleus: "Helium-4 nucleus (⁴He²⁺)",
    muon: "Muon (μ⁻)",
    antimuon: "Antimuon (μ⁺)",
    pionm: "Negative pion (π⁻)",
    pionp: "Positive pion (π⁺)",
    none: "None",
    initPosTitle: "Initial position",
    initVelTitle: "Initial velocity",
    initSpeedFrac: "Input the fraction of the initial speed with respect to the speed of light in vacuum ",
    svBtn: "Save changes and display system parameters",
    giAlert: "Success! Scroll down to check your input values",
    biAlert: "Check every input and try again",
    inputValues: "Input values",
    Quantity: "Quantity",
    Value: "Value",
    nullType: 'The electromagnetic field is of "null" type; that is, either both fields are null, or they are perpendicular and their magnitudes are such that (up to numerical precision)',
    electricType: 'The electromagnetic field is of "electric" type; that is, there exists an inertial frame such that the electric field is the only one present, and the magnetic field vanishes.',
    magneticType: 'The electromagnetic field is of "magnetic" type; that is, there exists an inertial frame such that the magnetic field is the only one present, and the electric field vanishes.',
    collinearType: 'The electromagnetic field is of "collinear" type; that is, there exists an inertial frame such that both fields are present and they are collinear, i.e., either parallel or antiparallel.',
    neglBoost: "<br>The boost parameter is null or negligible with respect to the scale of the system as given by the chosen parameters.",
    yesBoost: "<br>The boost to such inertial reference frame is characterized by a velocity with the following norm and unit direction:<br>",
    SystCharTitle: "System characterization",
    AnimPropLeg: "Animation properties:",
    inptCTFlbl: "Characteristic time factor:",
    Colours: "Colours",
    prtcl: "Particle",
    trail: "Trail",
    includeSpecFrame: "Include animation on special frame",
    includeCstmFrame: "Include animation on custom inertial frame",
    includeNonRelAnim: "Include non-relativistic animation",
    cstmBoostTitle: "Custom boost",
    cstmBoostFrac: "Input the fraction of the boost speed with respect to the speed of light in vacuum ",
    animBtn: "Show animation",
    gfiAlert: "Scroll down to see the animation",
    bfiAlert: "Check every input and try again"
  },
  es:
  {
    liSimul: "Simulación",
    liBgp: "Física de fondo",
    liCode: "Código",
    selLang: "Seleccione el idioma",
    decSep: ", ",
    cZeroToInf: "[0, ∞)",
    oZeroToInf: "(0, ∞)",
    minfToInf: "(-∞, ∞)",
    cZeroToOne: "[0, 1)",
    mainTitle: "Movimiento relativista de una partícula cargada y masiva en un campo electromagnético uniforme y constante",
    initCondF: "Condiciones iniciales: campos",
    EFtitle: "Campo eléctrico",
    MFtitle: "Campo magnético",
    MagnTitle: "Norma",
    UnitDirTitle: "Vector unitario",
    prBtn: "Pseudoaleatorio",
    SIPref: "Prefijo",
    initCondP: "Condiciones iniciales: partícula",
    inMassTitle: "Masa inercial",
    EChTitle: "Carga eléctrica",
    loadPreset: "Cargar preestablecido: ",
    electron: "Electrón (e⁻)",
    positron: "Positrón (e⁺)",
    proton: "Protón (p⁺)",
    antiproton: "Antiprotón (p⁻)",
    Helium4Nucleus: "Núcleo de Helio-4 (⁴He²⁺)",
    muon: "Muón (μ⁻)",
    antimuon: "Antimuón (μ⁺)",
    pionm: "Pión negativo (π⁻)",
    pionp: "Pión positivo (π⁺)",
    none: "Ninguno",
    initPosTitle: "Posición inicial",
    initVelTitle: "Velocidad inicial",
    initSpeedFrac: "Ingrese la fracción de la rapidez inicial respecto a la rapidez de la luz en el vacío ",
    svBtn: "Guardar los cambios y mostrar los parámetros del sistema",
    giAlert: "¡Éxito! Desplácese hacia abajo para comprobar sus valores de entrada",
    biAlert: "Verifique cada entrada e intente nuevamente",
    inputValues: "Valores de entrada",
    Quantity: "Cantidad",
    Value: "Valor",
    nullType: 'El campo electromagnético es de tipo "nulo"; es decir que ambos campos son nulos, o son perpendiculares y sus magnitudes son tales que (dentro del margen de precisión numérico)',
    electricType: 'El campo electromagnético es de tipo "eléctrico"; es decir que existe un marco de referencia inercial tal que el campo eléctrico es el único presente, y el campo magnético se anula.',
    magneticType: 'El campo electromagnético es de tipo "magnético"; es decir que existe un marco de referencia inercial tal que el campo magnético es el único presente, y el campo eléctrico se anula.',
    collinearType: 'El campo electromagnético es de tipo "colineal"; es decir que existe un marco de referencia inercial tal que ambos campos están presentes y son colineales (paralelos o antiparalelos).',
    neglBoost: "<br>El parámetro de <em>boost</em> es nulo o despreciable respecto a la escala del sistema dada por los parámetros ingresados.",
    yesBoost: "<br>El <em>boost</em> a tal marco de referencia se caracteriza por una velocidad con la siguiente magnitud y dirección:<br>",
    SystCharTitle: "Caracterización del sistema",
    AnimPropLeg: "Propiedades de la animación:",
    inptCTFlbl: "Factor de tiempo característico:",
    Colours: "Colores",
    prtcl: "Partícula",
    trail: "Estela",
    includeSpecFrame: "Incluir animación en el marco especial",
    includeCstmFrame: "Incluir animación en marco personalizado",
    includeNonRelAnim: "Incluir animación no relativista",
    cstmBoostTitle: "<em>Boost</em> personalizado",
    cstmBoostFrac: "Ingrese la fracción de la rapidez inicial respecto a la rapidez de la luz en el vacío ",
    animBtn: "Mostrar animación",
    gfiAlert: "Desplácese hacia abajo para ver la animación",
    bfiAlert: "Check every input and try again"
  },
  fr:
  {
    liSimul: "Simulation",
    liBgp: "Background physics",
    liCode: "Code",
    selLang: "Choisir la langue",
    decSep: " ; ",
    cZeroToInf: "[0, ∞[",
    oZeroToInf: "]0, ∞[",
    minfToInf: "]-∞, ∞[",
    cZeroToOne: "[0, 1[",
    mainTitle: "Mouvement relativiste d'une particule chargée et massive sur un champ électromagnétique uniforme et constant",
    initCondF: "Conditions initiales : champs",
    EFtitle: "Champ électrique ",
    MFtitle: "Champ magnétique ",
    MagnTitle: "Norme",
    UnitDirTitle: "Vecteur unitaire ",
    prBtn: "Pseudo-aléatoire",
    SIPref: "Préfixe",
    initCondP: "Conditions initiales : particule",
    inMassTitle: "Masse inertielle ",
    EChTitle: "Charge électrique ",
    loadPreset: "Charger par défaut : ",
    electron: "Électron (e⁻)",
    positron: "Positron (e⁺)",
    proton: "Proton (p⁺)",
    antiproton: "Antiproton (p⁻)",
    Helium4Nucleus: "Noyau d'hélium-4 (⁴He²⁺)",
    muon: "Muon (μ⁻)",
    antimuon: "Antimuon (μ⁺)",
    pionm: "Pion négatif (π⁻)",
    pionp: "Pion positif (π⁺)",
    none: "Aucune",
    initPosTitle: "Position initiale",
    initVelTitle: "Vitesse initiale ",
    initSpeedFrac: "Entrer la fraction de la vitesse initiale par rapport à la vitesse de la lumière dans le vide ",
    svBtn: "Enregistrer les modifications et afficher les paramètres système",
    giAlert: "Succès! Faites défiler vers le bas pour vérifier vos valeurs d'entrée",
    biAlert: "Vérifiez chaque entrée et réessayez",
    inputValues: "Valeurs d'entrée",
    Quantity: "Quantité",
    Value: "Valeur",
    nullType: "Le champ électromagnétique est de type « nul » ; c'est-à-dire que soit les deux champs sont nuls, soit ils sont perpendiculaires et leurs amplitudes sont telles que (jusqu'à la précision numérique)",
    electricType: "Le champ électromagnétique est de type « électrique » ; c'est-à-dire qu'il existe un référentiel inertiel tel que le champ électrique est le seul présent et le champ magnétique s'annule.",
    magneticType: "Le champ électromagnétique est de type « magnétique » ; c'est-à-dire qu'il existe un référentiel inertiel tel que le champ magnétique est le seul présent et que le champ électrique s'annule.",
    collinearType: "Le champ électromagnétique est de type « colinéaire » ; c'est-à-dire qu'il existe un cadre inertiel tel que les deux champs sont présents et qu'ils sont colinéaires, c'est-à-dire parallèles ou antiparallèles.",
    neglBoost: "<br>Le paramètre <em>boost</em> est nul ou négligeable par rapport à l'échelle du système donnée par les paramètres choisis.",
    yesBoost: "<br> Le <em>boost</em> vers un tel référentiel inertiel est caractérisé par une vitesse avec la norme et la direction unitaire suivantes : <br>",
    SystCharTitle: "Caractérisation du système",
    AnimPropLeg: "Propriétés des animations :",
    inptCTFlbl: "Facteur temps caractéristique :",
    Colours: "Couleurs",
    prtcl: "Particule",
    trail: "Sentier",
    includeSpecFrame: "Inclure l'animation sur le cadre de référence spécial",
    includeCstmFrame: "Inclure l'animation sur un cadre de référence personnalisé",
    includeNonRelAnim: "Inclure une animation non relativiste",
    cstmBoostTitle: "<em>Boost</em> personnalisé",
    cstmBoostFrac: "Entrer la fraction de la vitesse du <em>Boost</em> par rapport à la vitesse de la lumière dans le vide ",
    animBtn: "Show animation",
    gfiAlert: "Faites défiler vers le bas pour voir l'animation",
    bfiAlert: "Vérifiez chaque entrée et réessayez"
  },
  it:
  {
    liSimul: "Simulation",
    liBgp: "Background physics",
    liCode: "Code",
    selLang: "Seleziona la lingua",
    decSep: ", ",
    cZeroToInf: "[0, ∞)",
    oZeroToInf: "(0, ∞)",
    minfToInf: "(-∞, ∞)",
    cZeroToOne: "[0, 1)",
    mainTitle: "Moto relativistico di una particella carica e massiccia su un campo elettromagnetico uniforme e costante",
    initCondF: "Condizioni iniziali: campi",
    EFtitle: "Campo elettrico",
    MFtitle: "Campo magnetico",
    MagnTitle: "Norma",
    UnitDirTitle: "Vettore unitario",
    prBtn: "Pseudocasuale",
    SIPref: "Prefisso",
    initCondP: "Condizioni iniziali: particella",
    inMassTitle: "Massa inerziale",
    EChTitle: "Carica elettrica",
    loadPreset: "Caricare preimpostato: ",
    electron: "Elettrone (e⁻)",
    positron: "Positrone (e⁺)",
    proton: "Protone (p⁺)",
    antiproton: "Antiprotone (p⁻)",
    Helium4Nucleus: "Nucleo di elio-4 (⁴He²⁺)",
    muon: "Muone (μ⁻)",
    antimuon: "Antimuone (μ⁺)",
    pionm: "Pione negativo (π⁻)",
    pionp: "Pione positivo (π⁺)",
    none: "Nessuno",
    initPosTitle: "Posizione iniziale",
    initVelTitle: "Velocità iniziale",
    initSpeedFrac: "Immettere la frazione della velocità iniziale rispetto alla velocità della luce nel vuoto ",
    svBtn: "Salva le modifiche e mostra i parametri di sistema",
    giAlert: "Successo! Scorri verso il basso per controllare i valori di input",
    biAlert: "Controlla ogni input e riprova",
    inputValues: "Valori di input",
    Quantity: "Quantità",
    Value: "Valore",
    nullType: 'The electromagnetic field is of "null" type; that is, either both fields are null, or they are perpendicular and their magnitudes are such that (up tp numerical precision)',
    electricType: 'The electromagnetic field is of "electric" type; that is, there exists an inertial frame such that the electric field is the only one present, and the magnetic field vanishes.',
    magneticType: 'The electromagnetic field is of "magnetic" type; that is, there exists an inertial frame such that the magnetic field is the only one present, and the electric field vanishes.',
    collinearType: 'The electromagnetic field is of "collinear" type; that is, there exists an inertial frame such that both fields are present and they are collinear, i.e., either parallel or antiparallel.',
    neglBoost: "<br>The boost parameter is null or negligible with respect to the scale of the system as given by the chosen parameters.",
    yesBoost: "<br>The boost to such inertial reference frame is characterized by a velocity with the following norm and unit direction:<br>",
    SystCharTitle: "System characterization",
    AnimPropLeg: "Animation properties:",
    inptCTFlbl: "Characteristic time factor:",
    Colours: "Colours",
    prtcl: "Particle",
    trail: "Trail",
    includeSpecFrame: "Include animation on special frame",
    includeCstmFrame: "Include animation on custom inertial frame",
    includeNonRelAnim: "Include non relativistic animation",
    cstmBoostTitle: "Custom boost",
    cstmBoostFrac: "Input the fraction of the boost speed with respect to the speed of light in vacuum ",
    animBtn: "Show animation",
    gfiAlert: "Scroll down to see the animation",
    bfiAlert: "Check every input and try again"
  },
  pt:
  {
    liSimul: "Simulation",
    liBgp: "Background physics",
    liCode: "Code",
    selLang: "Selecione o idioma",
    decSep: ", ",
    cZeroToInf: "[0, ∞)",
    oZeroToInf: "(0, ∞)",
    minfToInf: "(-∞, ∞)",
    cZeroToOne: "[0, 1)",
    mainTitle: "Movimento relativístico de uma partícula carregada e massiva em um campo eletromagnético uniforme e constante",
    initCondF: "Condições iniciais: campos",
    EFtitle: "Campo elétrico",
    MFtitle: "Campo magnético",
    MagnTitle: "Norma",
    UnitDirTitle: "Vetor unitário",
    prBtn: "Pseudo-random",
    SIPref: "Prefixo",
    initCondP: "Condições iniciais: partícula",
    inMassTitle: "Massa inercial",
    EChTitle: "Carga elétrica",
    loadPreset: "Carregar predefinição:",
    electron: "Elétron (e⁻)",
    positron: "Pósitron (e⁺)",
    proton: "Próton (p⁺)",
    antiproton: "Antipróton (p⁻)",
    Helium4Nucleus: "Núcleo de Hélio-4 (⁴He²⁺)",
    muon: "Múon (μ⁻)",
    antimuon: "Antimúon (μ⁺)",
    pionm: "Píon negativo (π⁻)",
    pionp: "Píon positivo (π⁺)",
    none: "Nenhum",
    initPosTitle: "Posição inicial",
    initVelTitle: "Velocidade inicial",
    initSpeedFrac: "Insira a fração da velocidade inicial em relação à velocidade da luz no vácuo ",
    svBtn: "Salve as alterações e mostre os parâmetros do sistema",
    giAlert: "Sucesso! Role para baixo para verificar seus valores de entrada",
    biAlert: "Verifique todas as entradas e tente novamente",
    inputValues: "Valores de entrada",
    Quantity: "Quantidade",
    Value: "Valor",
    nullType: 'The electromagnetic field is of "null" type; that is, either both fields are null, or they are perpendicular and their magnitudes are such that (up tp numerical precision)',
    electricType: 'The electromagnetic field is of "electric" type; that is, there exists an inertial frame such that the electric field is the only one present, and the magnetic field vanishes.',
    magneticType: 'The electromagnetic field is of "magnetic" type; that is, there exists an inertial frame such that the magnetic field is the only one present, and the electric field vanishes.',
    collinearType: 'The electromagnetic field is of "collinear" type; that is, there exists an inertial frame such that both fields are present and they are collinear, i.e., either parallel or antiparallel.',
    neglBoost: "<br>The boost parameter is null or negligible with respect to the scale of the system as given by the chosen parameters.",
    yesBoost: "<br>The boost to such inertial reference frame is characterized by a velocity with the following norm and unit direction:<br>",
    SystCharTitle: "System characterization",
    AnimPropLeg: "Animation properties:",
    inptCTFlbl: "Characteristic time factor:",
    Colours: "Colours",
    prtcl: "Particle",
    trail: "Trail",
    includeSpecFrame: "Include animation on special frame",
    includeCstmFrame: "Include animation on custom inertial frame",
    includeNonRelAnim: "Include non relativistic animation",
    cstmBoostTitle: "Custom boost",
    cstmBoostFrac: "Input the fraction of the boost speed with respect to the speed of light in vacuum ",
    animBtn: "Show animation",
    gfiAlert: "Scroll down to see the animation",
    bfiAlert: "Check every input and try again"
  },
};
